### ISSUE TITLE
Mozilla and IE issues

### ISSUE THREAD

**Issue by jw1990** [nicinabox/superslides#12]
There's a small issue I'm having.  I've gotten the slider to work perfectly in Chrome. 

I have text overlayed on top of the images on each slide. In Firefox, when you hit the next button the text is slightly delayed in showing up. Not a huge problem, but I'd like it if the text arrived together with the image like it does in Chrome.

Also, in IE when the next button is hit, the text from the previous slide overlaps onto the text for the next slide for a couple seconds. 

I've tried everything I can think of and nothing has fixed these two problems. If anyone could help it'd be very much appreciated.

**Comment by nicinabox** [comment]
Could you share your code? It will be helpful with debugging.

**Comment by jw1990** [comment]
Sorry about that!

style.css

http://pastebin.com/brerEwF3

index.php

http://pastebin.com/uwwJkSGY

**Comment by nicinabox** [comment]
This is actually not an issue with Superslides. You're using `position: fixed` on your content. It's very interesting that this works in Chrome, because fixed position removes an element from the document flow. It's parent has `overflow:hidden` and this shouldn't change how the fix position element is shown.

My suggestion is to change your quote css to `position: absolute`.

```
.contain-quote {
  position: absolute;
}
```

**Comment by jw1990** [comment]
Thank you very very much for taking the time to look at my code. It's working perfectly in all browsers now.
I appreciate it.

**Comment by nicinabox** [comment]
Excellent!
