### ISSUE TITLE
Prevent large images from being cropped.

### ISSUE THREAD

**Issue by sergiotapia** [nicinabox/superslides#157]
Hello,

On my home page I'm displayed the Superslides element with about 5 image slides.

The problem is that some images are very tall, and others just normal picture-like ratios. Superslides is cutting off the tops and bottom of the very tall images.

See screenshot:
![screen shot 2013-09-26 at 8 48 17 am](https://f.cloud.github.com/assets/686715/1217541/16b39c0c-26aa-11e3-9869-727e658124bb.png)

The actual original image:
![screen shot 2013-09-26 at 8 48 50 am](https://f.cloud.github.com/assets/686715/1217542/16d3b352-26aa-11e3-8472-2f1d5a9c1a4b.png)

How can I make the images stretch to fit height or width depending on which is larger?

**Comment by sergiotapia** [comment]
Ok, so adding the `.preserve` class to the images no longer resizes them, yay!

But the images are no longer centered. :(

![screen shot 2013-09-26 at 9 22 13 am](https://f.cloud.github.com/assets/686715/1217737/b23275d2-26ae-11e3-9b0d-bb6ccc3eff3a.png)

Any ideas?

**Comment by nicinabox** [comment]
`.preserve` is intended to be used in content areas where you may have a headshot or icon or something like that. It's not for the background slides.

Images stretch to fit the window using the math behind `background-size: cover`. Obviously if you have a tall image and you put it in a wide viewport, there will be space on the sides. Those empty sized need be be covered, and the only way to do that is by "zooming" the image. Otherwise you end up with a squished image and that's no good. 

Superslides doesn't do letterboxing. I recommend using images that are similar to the viewport size.
