### ISSUE TITLE
Autoplay feature

### ISSUE THREAD

**Issue by hejamartin** [nicinabox/superslides#43]
Hi, 

There is a play:true setting, and that works. But I would like to have a delay-setting. So that the slide keeps still XX seconds before moving on.

I have been digging through the code, but this does seem to be absent.
Is there a way to do this?

Martin

**Comment by nicinabox** [comment]
Sorry, I need to clear up some confusion in the option and documentation. Use the delay as the value: `play: 5000`

**Comment by sharksharkco** [comment]
Hi, I don't believe this is solved. Play 5000 will change the animation speed but not add a delay. 

I believe what he was asking (and what I'm asking is) for instance, the first slide loads and is visible for 7000ms, then after 7000ms, the 5000ms animation will occur sliding to the next slide. Once there, the second slide will remain for 7000ms, and so on.

I've been trying to figure out this effect as well with no luck :(

Any ideas?

**Comment by nicinabox** [comment]
Hmm, the code says otherwise: https://github.com/nicinabox/superslides/blob/0.6-stable/src/core_prototype.js#L122-L130

`play` is a delay interval. As in "Play and move every n seconds". 
Animation speed is controlled with a separate option (`animation_speed`, conveniently): https://github.com/nicinabox/superslides/blob/0.6-stable/src/fx.js#L14

**Comment by sharksharkco** [comment]
You are correct, I apologize. Long day looking at the same thing. Thank you for the clarification and your time. This plugin is the bee's knees.

**Comment by nicinabox** [comment]
Ha, glad you got it worked out :)
